[package]
name = "SpaceSandbox"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "*"
subprocess = "*"
libc = "0.2"

[dependencies.engine]
path = "engine"

[build-dependencies]
subprocess = "*"