[package]
name = "SpaceSandbox"
version = "0.1.0"
edition = "2021"
default-run = "SpaceSandbox"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit      = "0.27.4"
ash        = "0.36.0"
num        = "0.2"
cgmath     = "0.17.0"
image      = "0.22"
memoffset  = "0.5.1"
tobj       = "3.2.2"
log        = "0.4.17"
simplelog  = "0.10.1"
ash-window = "0.9.1"
vk-shader-macros = "0.2.2"
nalgebra = "0.31.1"
nalgebra-glm = "0.17.0"
egui-winit-ash-integration = {path = "ext/egui-winit-ash-integration" }
gpu-allocator = "0.17.0"
egui = "0.19.0"
gltf = { version = "1.0.0", features = ["KHR_materials_pbrSpecularGlossiness"] }
byteorder = "1.4.3"
rayon = "1.5.3"
specs = "0.18.0"
egui-gizmo = "0.8.0"
wgpu = "0.13"
pollster = "0.2"
tokio = "1.21.2"
encase = {version = "0.3.0", features = ["nalgebra"] }
crevice = {version = "0.11.0", features = ["nalgebra"] }
bytemuck = { version = "1.4.1", features = [ "derive" ] }
glam = "0.21.3"



