[package]
name = "SpaceSandbox"
version = "0.1.0"
edition = "2021"
default-run = "SpaceSandbox"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit      = "0.26.1"
ash        = "0.36.0"
num        = "0.2"
cgmath     = "0.17.0"
image      = "0.22"
memoffset  = "0.5.1"
tobj       = "3.2.2"
log        = "0.4.17"
simplelog  = "0.10.1"
ash-window = "0.9.1"
vk-shader-macros = "0.2.2"
vk-mem = "0.2.2"
nalgebra = "0.31.1"
nalgebra-glm = "0.17.0"
egui-winit-ash-integration = {path = "egui-winit-ash-integration"}
gpu-allocator = "0.17.0"
egui = "0.16.1"
gltf = "1.0.0"
byteorder = "1.4.3"

[workspace]
members = [
    "egui-winit-ash-integration"
]