[package]
name = "SpaceSandbox"
version = "0.1.0"
edition = "2021"
default-run = "SpaceSandbox"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit      = "0.27.4"
num        = "0.2"
image      = "0.22"
tobj       = "3.2.2"
log        = "0.4.17"
simplelog  = "0.10.1"
nalgebra = "0.31.1"
egui = "0.19.0"
gltf = { version = "1.0.0", features = ["KHR_materials_pbrSpecularGlossiness"] }
byteorder = "1.4.3"
rayon = "1.5.3"
legion = "0.4.0"
egui-gizmo = "0.8.0"
wgpu = "0.14"
pollster = "0.2"
tokio = "1.21.2"
encase = {version = "0.3.0", features = ["nalgebra"] }
bytemuck = { version = "1.4.1", features = [ "derive" ] }
bevy = "0.9.0"
serde = "*"

js-sys = "0.3.51"
wasm-bindgen = "0.2.74"
wasm-bindgen-futures = "0.4.23"

space_macros = {path = "crates/space_macros"}
space_shaders = {path = "crates/space_shaders"}
space_code_editor = {path = "crates/space_code_editor"}
space_core = {path = "crates/space_core"}
space_assets = {path = "crates/space_assets"}
space_render = {path = "crates/space_render"}
space_game = {path = "crates/space_game"}

downcast-rs = "1.2.0"
egui_wgpu_backend = "0.19"
egui_winit_platform = "0.16"

[workspace]
members = [
    "crates/space_macros",
    "crates/space_shaders",
    "crates/space_core",
    "crates/space_assets",
    "crates/space_code_editor",
    "crates/space_render",
]
#
#[lib]
#crate-type = ["cdylib", "rlib"]